name: Android build
on:
  push:
    branches: [mubashir]
jobs:
  Android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Install npm dependencies
        run:  npm install

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          
      - name: Caching ruby dependencies
        uses: actions/cache@v2
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-gems-${{ secrets.GEMS_CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Caching Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install dependencies to support ruby project
        run:  |
          cd android
          bundle config --global set deploy_platform_default x86_64-linux
          bundle install 
      
#       - name: Configure Keystore
#         run: |
#           echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
#           base64 -d -i keystore.jks.b64 > app/keystore.jks
#           echo "storeFile=keystore.jks" >> keystore.properties
#           echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
#           echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
#           echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
#         env:
#           ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
#           KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
#           KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
#           KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Create Google Play Config file
        run : |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
          ls
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
          

      - name: Build and distribute app
        run: |
          cd android
          ls
          chmod +x gradlew
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          git config --global user.email ${{github.event.pusher.email}}
          git config --global user.name ${{github.event.pusher.name}}
          bundle exec fastlane build_and_distribute
