name: Linux Build on PR

'on': pull_request
jobs:
  snap-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup npm package
        run: npm install
      - name: Build Using npm
        run: node_modules/.bin/ng build
      - name: snap package
        run: npm run package-linux
