name: Build Project on PR
'on': pull_request
jobs:
  angular-build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup npm package
        run: npm install
      - name: Build Using npm
        run: node_modules/.bin/ng build
