
name: File build
on:
  push:
    branches: [mubashir]
jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        
        run: |
          cd downloads
          echo storeFile=my-release-key.jks > keystore.properties
          cd ..
#     echo storePassword="$KEYSTORE_KEY_PASSWORD" > keystore.properties
#           echo keyAlias="$KEYSTORE_KEY_ALIAS" > keystore.properties
#           echo keyPassword="$KEYSTORE_KEY_PASSWORD" > keystore.properties
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
