name: Snapcraft Publish Action
on:
  push:
    branches: [mubashir]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: ls
    - run: cd snap/
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: edge
